"""phase_2_webhooks_and_ingestion

Revision ID: 39030255bf15
Revises: c87e4445dd70
Create Date: 2026-09-19 16:37:51.786319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39030255bf15'
down_revision = 'c87e4445dd70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_subscriptions',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('secret', sa.String(length=128), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_subscriptions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('webhook_deliveries',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['webhook_subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_subscription_id'), ['subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_event'))

    op.drop_table('webhook_deliveries')
    with op.batch_alter_table('webhook_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_subscriptions_tenant_id'))

    op.drop_table('webhook_subscriptions')
    # ### end Alembic commands ###
