"""phase_1_advanced_ai_engine

Revision ID: c87e4445dd70
Revises: b4c0bd8ae6f7
Create Date: 2026-09-19 16:33:43.280156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87e4445dd70'
down_revision = 'b4c0bd8ae6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_categories',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('action_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tenant_category_name')
    )
    with op.batch_alter_table('custom_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_categories_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('email_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sub_category', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('sentiment', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('urgency', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('confidence_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('in_quarantine', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('fraud_risk_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fraud_flags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('extracted_entities', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tone_used', sa.String(length=30), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_email_analyses_thread_id'), ['thread_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_analyses_thread_id'))
        batch_op.alter_column('category',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('tone_used')
        batch_op.drop_column('extracted_entities')
        batch_op.drop_column('fraud_flags')
        batch_op.drop_column('fraud_risk_score')
        batch_op.drop_column('in_quarantine')
        batch_op.drop_column('confidence_score')
        batch_op.drop_column('urgency')
        batch_op.drop_column('sentiment')
        batch_op.drop_column('sub_category')
        batch_op.drop_column('thread_id')

    with op.batch_alter_table('custom_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_categories_tenant_id'))

    op.drop_table('custom_categories')
    # ### end Alembic commands ###
